name: DDWhitelist
main: dev.datadecay.ddwhitelist.DDWhitelist
version: ${project.version}
api-version: 1.20
author: DataDecay
description: A simple permission based whitelist plugin.

dependencies:
  server:
    Essentials:
      load: AFTER
      required: true
    PlaceholderAPI:
      load: AFTER
      required: true

commands:
  ddwhitelist:
    description: Manage the whitelist
    aliases: [ddwl, whitelist]
    usage: /<command> <on|off|status|help>

permissions:
  ddwhitelist.toggle:
    description: Allows toggling whitelist
    default: op
  ddwhitelist.allowjoin:
    description: Allows a player to join when whitelist is enabled
    default: op
  ddwhitelist.allowjoin.*:
    description: Allows a player to join specific servers by server name
    default: false